UoEMainLibrary/skylight-local

theme-local/clds/css/style.css
theme/clds/views/header.php

Collections Online Changes (following P&I review)
- Reduce size of white boxes on home page
- Remove Wordpress logo on black header
- Rename Research tab to Projects
- Reduce prominence of Facet blobs on CLD search results

LIB001-1006 Collections Online Changes (following P&I review)

---

config/openbooks.is.ed.ac.uk.php
config/sopacollection.ph.ed.ac.uk.php
theme/openbooks/views/index.php
theme/openbooks/views/search_results.php
theme/physics/views/record.php
theme/physics/views/search_results.php

Changes to OpenBooks front page ad config. Changes to search results appearance.

LIB001-1367 OpenBooks changes

---

config/piccolo.php

LIB001-1380 Piccolo config

---

config/exhibitions.ed.ac.uk.php

Literally add one field to record display line.

LIB001-1474 Add Identifier to Exhibitions record display

---

theme/alumni/views/header.php
theme/anatomy/views/header.php
theme/art/views/header.php
theme/calendars/views/header.php
theme/clds/views/header.php
theme/exams/views/header.php
theme/exhibitions/views/header.php
theme/fairbairn/views/header.php
theme/iconics/views/header.php
theme/images/views/header.php
theme/iog/views/header.php
theme/mimed/views/header.php
theme/openbooks/views/header.php
theme/physics/views/header.php
theme/projects/views/header.php
theme/rocks/views/header.php

- replace bootstrap location on other projects

LIB001-1462 Piccolo online responsive design

---

config/alumni.php
static/alumni/about.php
static/alumni/earlyvet.php
static/alumni/extraac.php
static/alumni/femalegrad.php
static/alumni/firstmat.php
static/alumni/medsample.php
static/alumni/newcoll.php
static/alumni/roll.php
static/alumni/rosner.php
static/alumni/vetgrad.php
static/alumni/women.php
theme/alumni/views/index.php
theme/alumni/views/record.php
theme/alumni/views/search_results.php

Add static page for each collection
Amend index.php for links
Amend record page for better handling of collection
Amend search results to show collection and date
Amend config alumni.php (I know this should not be in git) to allow correct date filter, static array,  new field (anchor date)

LIB001-1198 Alumni static pages and links

---

config/alumni.php
static/exams/index.php
theme/alumni/views/search_results.php

Quick fixes to alumni search results.
Exam papers- update to reflect 2015-16 diet in.

LIB001-1198 More alumni search result fixes

---

theme/clds/views/record.php

Change so the PDF and image do not conflict on a CLD

LIB001-1533 Handlist - no PDF viewer

---

config/alumni.php
config/openbooks.is.ed.ac.uk.php
static/alumni/about.php
static/alumni/femalegrad.php
static/alumni/firstmat.php
static/alumni/medsample.php
static/alumni/rosner.php
static/alumni/vetgrad.php
theme/alumni/views/advanced_search.php
theme/alumni/views/div_main_end.php
theme/alumni/views/feedback.php
theme/alumni/views/header.php
theme/alumni/views/index.php
theme/alumni/views/search_results.php
theme/openbooks/views/record.php
theme/physics/views/record.php

Alumni changes to capture most recent requests from Grant. Physics change to surface JPGS, not TIFFS.

LIB001-1637 Alumni and Physics records

---

config/skylight.php

Add alumni to the list of allowed suffixes for collections just so it can go live.

LIB001-1728 Add alumni to skylight.php

---

config/alumni.php

Just add an option on community for Alumni- the numbers are different between test and live (a symptom of the length of time it's been hanging around waiting to be implemented).

LIB001-1736 Alumni config test/live switch for community

---

config/alumni.php
theme/alumni/views/index.php
theme/alumni/views/record.php

Three post-live bugfixes:
1. Link to laureation degree album
2. Wrong name for static page in config file for female graduates
3. See all records link on record page not resolving correctly

LIB001-1741 Alumni post-live bug fixes

---

theme/mimed/views/record.php
theme/physics/views/header.php
theme/physics/views/record.php

Change the following files
theme/physics/record.php (add video and audio)
theme/physics/header.php (add flowplayer.js)
theme/mimed/record.php (add controls=true where webm/chrome)

LIB001-1678 Physics videos and MIMEd chrome controls on webms

---

config/alumni.php
static/alumni/ww1roll.php
theme/alumni/views/index.php

Changes to bring in alumni World War 1 Roll of Honour.
New: static/alumni/ww1roll.php
Altered: theme/alumni/views/index.php
Altered: config/alumni.php
Dataload required and fields dc.coverage.temporalbirth and dc.coverage.temporal.birth to be added to dspace.

Lib001 1757

---

config/towardsdolly.php
static/towardsdolly/about.php
static/towardsdolly/catalogues.php

Changed files:
config/towardsdolly.php - add in new catalogue
static/catalogues.php- add link for one catalogue
static/about.php- add link for the project report
Also, remember to add the Towards Dolly complete final report.pdf to the videos folder (which now covers any static page media, not just video).

LIB001-1766 Towards Dolly project report

---

static/openbooks/unavailable.php
theme-local/openbooks/css/style.css
theme-local/physics/css/style.css
theme/alumni/views/index.php
theme/openbooks/views/record.php
theme/openbooks/views/recordwait.php
theme/openbooks/views/search_results.php

New files
static/openbooks/unavailable.php
Altered files
theme/openbooks/views/search_results.php - change to stop PDF download appearing where there is more than one, and to go to this unavailable page if there is no PDF
theme/openbooks/views/record.php- add support for image, video and audio. Don't know if it will be required, but it is there now.
theme-local/openbooks/css/style.css - tidy up in line with above
theme-local/physics/css/style.css - tidy up in line with above (noticed latterly)
Also
theme/alumni/views/index.php-typo in link

LIB001-1765 Open Books tidyup

---

theme-local/stcecilia/css/style.css
theme/stcecilia/views/header.php
theme/stcecilia/views/record-tabbed.php
theme/stcecilia/views/record.php
theme/stcecilia/views/recordfixing.php

Changes to record, header and style.css. This is just so we can merge together.

LIB001-1797 Some StCecilia changes- not final

---

theme/art/views/record.php
theme/art/views/search_results.php

Just getting more things into the iiif branch.

IIIF More changes for art

---

static/exams/faqs.php

Quick changes to static/exams/faqs.php

LIB001-1795 Last Exam Papers Changes

---

theme/physics/views/record.php

Fix record.php under theme/views/physics.

LIB001-1839 Physics image display problem

---

theme-local/iconics/css/style.css
theme/iconics/views/header.php
theme/iconics/views/record.php

Change to 
theme/iconics/views/record.php- openseadragon integration
theme/iconics/views/header.php- openseadragon integration
theme-local/iconics/css/style.css- openseadragon integration

LIB001-1840 Iconics IIIF Zooming

---

theme-local/iconics/css/style.css
theme-local/stcecilia/css/style.css
theme/iconics/views/index.php
theme/iconics/views/record.php
theme/stcecilia/views/footer.php
theme/stcecilia/views/header.php
theme/stcecilia/views/index.php
theme/stcecilia/views/record-zoom.php
theme/stcecilia/views/search_results.php

Iconics drag and drop fixes
St Cecilias to master

LIB001-1840 Iconics changes plus St Cecilia to master

---

theme/stcecilia/views/record.php

Wee fix for uncompiling record.php in stcecilias.

LIB001-1840 St Cecilias error fix

---

static/iconics/iiif.php
theme-local/iconics/css/style.css
theme/iconics/views/index.php
theme/iconics/views/random_items.php
theme/iconics/views/record.php
theme/stcecilia/views/record.php
theme/stcecilia/views/related_items.php

Iconics drag and drop first pass. 
Also some st cecilias stashing...

LIB001-1840 Iconics drag and drop

---

theme/art/views/record.php
theme/art/views/search_results.php

Move back the non-IIIF code for Art.

LIB001-1859 Art to non-IIIF

---

config/stcecilia.php

Rogue localhost variable kicking about in config.

LIB001-1864 Localhost st cecilia removal

---

config/skylight.php
theme-local/coimbra/css/style.css
theme/coimbra/views/index.php
theme/coimbra/views/search_results.php

Tried to fix bugs showing on safari and chrome(Header becomes higher, text too small)
Changed the way records are displayed in search_results. Now we show the record name on mobile devices and the new structure is easier to maintain.
Fixed bugs with masonry display on chrome and tablet
Cleared a lot of css and divided search_results code in media blocks as the version for mobile and desktop had many differences.

Index page, Record page after tablet testing

---

theme-local/stcecilia/js/script.js
theme/alumni/views/header.php
theme/anatomy/views/header.php
theme/art/views/header.php
theme/audio/views/header.php
theme/calendars/views/header.php
theme/clds/views/header.php
theme/coimbra/views/feedback.php
theme/coimbra/views/header.php
theme/exams/views/header.php
theme/exhibitions/views/header.php
theme/fairbairn/views/header.php
theme/iconics/views/header.php
theme/iconicsdeepzoom/views/header.php
theme/images/views/header.php
theme/iog/views/header.php
theme/lhsacasenotes/views/header.php
theme/mimed/views/header.php
theme/openbooks/views/header.php
theme/physics/views/header.php
theme/piccolo/views/header.php
theme/projects/views/header.php
theme/public-art/views/header.php
theme/rocks/views/header.php
theme/sch/views/header.php
theme/stcecilia/views/header.php
theme/towardsdolly/views/header.php

Changes to make all included links and stylesheets non-http (so https if possible, but in general downloaded to skylight assets).

LIB001-1937 https mixed content fixes

---

config/stcecilias.php

New file- stcecilias.php . Do not require to change references to stcecilia as folder names.
Working on same JIRA as other small fix, apologies.

LIB001-1937 Change stcecilia to stcecilias

---

static/exams/index.php
theme-local/stcecilia/css/style.css
theme/mimed/views/record.php

Make MIMED OS Zoom be 1 instead of 3
Make St Cecilias reference IIIF on front page
Make Exams reference correct exams diet

LIB001-2063 Mimed zoom level, StC IIIF front page, Exams static index

---

theme-local/clds/css/style.css
theme/clds/views/index.php

Wee change to CSS and index page so boxes in right order and font sizes work when crushed.

LUC023A-61 Fix to front page

---

config/mimed.php
theme/mimed/views/record.php

Changes in record and config files for MIMED for Schema.org project.

LUC023A-64 schema.org changes for mimed

---

config/art.php
config/calendars.php
theme/art/views/record.php
theme/calendars/views/record.php

Schema markup implementation for Art and Calendars.

LUC023A-64

---

config/exampapers.ed.ac.uk.php
config/exhibitions.ed.ac.uk.php
config/fairbairn.ac.uk.php
config/guardbook.php
config/iconics.php
config/openbooks.is.ed.ac.uk.php
theme/exams/views/record.php
theme/exhibitions/views/record.php
theme/fairbairn/views/record.php
theme/guardbook/views/record.php
theme/iconics/views/record.php
theme/openbooks/views/record.php

Updated files for the schema.org project. Files covered:
1. Openbooks
2. Guardbook
3. Iconics
4. Exampapers
5. Exhibitions
6. Fairbairn

LUC023A-64 schema project

---

theme/archivemedia/views/record.php

LUC023A-74 PDFS

---

theme/archivemedia/views/record.php

Bug re multiple pdfs and php error on non-pdf items.

LUC023A-83 ArchiveMedia bug

---

config/geddes.php
theme/geddes/views/record.php

Geddes Digital Objects: provide a title where possible. If not, don't execute that line.

LUC024A-11 Allow non-titled images (Geddes)

---

theme/clds/views/index.php

Change to theme/clds/views/index.php- name is incorrect.

LUC023A-95 Early English Drama replaces Shakespeare Folios

---

theme/stcecilia/views/search_results.php

Change to improve appearance of search results on iOS devices, and to stop long thin ones looking ridiculous.

LUC023A-99 St Cecilias search results improvement

---

config/coimbra-colls-vanilla.php

Should be 74 for live (for the dummy Coimbra collection).

LUC023A-107 Correct container ID

---

theme-local/public-art/js/openseadragonconfig.js
theme-local/public-art/map/main.js
theme/public-art/views/header.php

Just changed explicit references to test.collections.ed in header to base_url, and some explicit references to collections until such times as we can do this cleanly.

LUC023A-108 Public Art relativity

---

static/art/about.php

Change to static about page for art.

LUC023A-111 Change contact details from Lebeter to Delaney

---

config/art.php
config/geddes.php
theme-local/art/css/style.css
theme-local/geddes/css/style.css
theme/art/views/record.php
theme/geddes/views/index.php
theme/geddes/views/record.php
theme/geddes/views/search_facets.php
theme/geddes/views/search_results.php
theme/stcecilia/views/search_facets.php

Changes for release 2.17.3:
Geddes look and feel changes
St Cecilias "More..."
Art Sketchfab

Luc023 a 117

---

static/exhibitions/conectando.php

Adding an image to the Oscar Romero podcast ref.

LUC023A-128 Conectando

---

theme-local/coimbra-colls/css/style.css

These should have live references.

LUC023A-125 Not test background images

---

static/coimbra-colls/about.php
static/coimbra-colls/virtual-exhibition.php
theme-local/coimbra-colls/css/style.css

static/coimbra-colls/about.php
static/coimbra-colls/virtual-exhib.php
CSS

LUC023A-125 Coimbra Colls About page

---

theme/coimbra-colls/views/header.php

LUC023A-125 Should say Coimbra Group Collections

---

theme/coimbra-colls/views/index.php

Bug affecting music category on coimbra colls. Stray %.

LUC023A-125 Fix Musical Instruments bug

---

theme-local/coimbra-colls/css/style.css
theme/coimbra-colls/views/index.php

Text on its side- the way I was doing it was causing linking target issues. I've changed to normal temporarily till I find a better solution.

LUC023A-125 text off side

---

theme-local/coimbra/css/style.css
theme/art/views/record.php

Coimbra text direction
Metadata games link

Luc023 a 125

---

static/clds/accessibility.php

LUC023A-159 Accessibility- closing bracket

---

theme-local/umis/css/style.css
theme/umis/views/index.php

LUC023A-162 UMIS content

---

theme/coimbra-colls/views/record.php

Buttons were pointing to a hardcoded theme

LUC023A-168 Coimbra Colls Seadragon buttons

---

static/umis/top-picks.php
theme-local/umis/css/style.css

LUC023A-162 UMIS content- top picks page

---

static/coimbra-colls/about.php

Add a few lines of text to about page on coimbra-colls

LUC023A-171 about page shy on text

---

theme/coimbra-colls/views/header.php
theme/coimbra/views/header.php
theme/exhibitions/views/div_main_end.php
theme/umis/views/feedback.php
theme/umis/views/header.php

Change API key for Google Maps. Temporary just now- we want to move to OpenStreetMap

LUC023A-192 New API for Google Maps

---

static/bodylanguage/about.php
static/bodylanguage/catelogue.php
static/bodylanguage/contact.php
static/bodylanguage/people.php
theme-local/bodylanguage/css/bodylanguage.css
theme/bodylanguage/views/div_main_end.php
theme/bodylanguage/views/header.php
theme/bodylanguage/views/healthcheck.php
theme/bodylanguage/views/index.php
theme/bodylanguage/views/random_items.php
theme/bodylanguage/views/random_items_none.php
theme/bodylanguage/views/recent_items.php
theme/bodylanguage/views/record.php
theme/bodylanguage/views/related_items.php
theme/bodylanguage/views/search_facets.php
theme/bodylanguage/views/search_results.php

Commit recovering lost work 06/2020

Luc023 a p042

---

config/guardbook.php
config/iconics.php
config/skylight.php
config/stuartsound.is.ed.ac.uk.php
theme/guardbook/views/search_facets.php

adjusted container_id's for guardbook, iconics, and stuartsound. 
changed skylight.php proxyurl to open PDF's appropriately and added skylight_filter_exact and skylight_filter_sort to fit the needs of dspace_library_6.
changed guardbook to point on dpsace_6 instead of exams as needes for the php7 branch in skylight

Adjusted configs for guardbook, iconics, stuartsound, and skylight.php

---

static/alumni/accessibility.php
static/cockburn/accessibility.php
static/coimbra-colls/accessibility.php
static/eerc/accessibility.php
static/fairbairn/accessibility.php
static/rocks/accessibility.php
theme/alumni/views/div_main_end.php
theme/coimbra-colls/views/footer.php
theme/eerc/views/footer.php
theme/fairbairn/views/div_main_end.php
theme/rocks/views/div_main_end.php

Added AS to the sites:
- Alumni
- Coimbra Colls
- EERC
- Fairbairn
- Geology

Added Accessibility statements

---

static/calendars/accessibility.php
static/guardbook/accessibility.php
static/piccolo/accessibility.php
static/public-art/accessibility.php
theme-local/public-art/css/style.css
theme/calendars/views/div_main_end.php
theme/guardbook/views/footer.php
theme/piccolo/views/footer.php

- Stuartsound
- Calendars
- Guardbooks
Fixed an issue on public-arts inside the style.css where list elements listend globally to float:left which caused a bit wonky looking AS.

Added additional AS

---

config/alumni.php
config/archivemedia.php
config/cockburn.php
config/exhibitions.ed.ac.uk.php
config/openbooks.is.ed.ac.uk.php
config/public-art.php
config/sopacollection.ph.ed.ac.uk.php

A few outstanding DSpace 6 UUIDs

Luc023 a 194

---

config/clds.php
theme/clds/views/record.php
theme/clds/views/search_results.php

Changes to urlencode for dodgy filenames, reduce length of title etc.

LUC023A-202 Quick CLD image fixes

---

theme-local/stcecilia/css/style.css
theme/stcecilia/views/index.php
theme/stcecilia/views/record.php

Just a quick fix to the grid layout issue flagged during the progress meeting

Search results and metadata layout update

---

config/archivemedia.php

Add dc.type.en to related items in config for archivemedia.php to ensure items DO come through.

LUC023A-207 ArchiveMedia dc.type into related items

---

theme/pointsofarrival/views/index.php

Initial commit to after fixing git repo issues for PoA

Initial commit of git re-clone for PoA

---

theme/stcecilia/views/record.php

Test to fix container_id config issues

StCs - Record meta update, config container_id update

---

config/speccoll.php
theme/arch-dig/views/record.php
theme/mimed/views/record.php
theme/mimed/views/search_results.php

replace | on MIMEd search_results and record with &nbsp;
some config items missing on speccoll and arch-dig.

LUC023A-207 MIMEd pipe replace/Speccoll-Arch-dig config

---

theme/archivemedia/views/div_main_end.php
theme/bodylanguage/views/div_main_end.php
theme/calendars/views/div_main_end.php
theme/clds/views/footer.php
theme/eerc/views/footer.php
theme/geddes/views/footer.php
theme/guardbook/views/footer.php
theme/iconics/views/div_main_end.php
theme/lhsacasenotes/views/footer.php
theme/mimed/views/div_main_end.php
theme/openbooks/views/div_main_end.php
theme/piccolo/views/footer.php
theme/rocks/views/div_main_end.php
theme/speccoll/views/footer.php
theme/towardsdolly/views/div_main_end.php

Just a change to links for takedown policies.

Luc023 a 207

---

theme/clds/views/footer.php

Wee change to how it's displayed.

LUC023A-207 Takedown policy main page

---

theme/arch-dig/views/record.php
theme/pointsofarrival/views/poa_sidebar.php

Check on catalogue entry as well as link.

LUC023A-209 Arch-dig catalogue entry not showing

---

.gitignore

No need for a review. Is just a simple .gitignore update

gitignore update to avoid large image files that are not needed

---

static/pointsofarrival/contact.php
theme-local/pointsofarrival/css/style.css

- Removal of hard-coded test.collections urls
- Gorbals image reduction to be web friendly
- Contact heading padding

More PoA fixes

---

theme-local/pointsofarrival/css/style.css

- Fixing the margins on the religions list

Fix to lists

---

config/art.php

LUC023A-210 Art config fix

---

static/clds/collections-as-data.php
theme-local/clds/css/style.css
theme/clds/views/index.php

Collections.ed front page link, collections-as-data static page improvements.

LUC023A-211 Collections as Data link

---

config/exhibitions.php

LUC023A-212 Exhibitions config

---

config/sopacollection.ph.ed.ac.uk.php

Just fix the config for sopacollection.ph.ed.ac.uk to look at correct collection in test.

LUC023A-216 fix sopacollection container in test

---

config/bodylanguage.php
config/fairbairn.ac.uk.php
config/lhsacasenotes.php
config/towardsdolly.php

Luc023 209

---

theme/art/views/index.php

Paolozzi image requires resize for carousel (Art)

LUC023A-217 Paolozzi image fix

---

static/alumni/accessibility.php
static/archivemedia/accessibility.php
static/art/accessibility.php
static/calendars/accessibility.php
static/clds/accessibility.php
static/cockburn/accessibility.php
static/coimbra-colls/accessibility.php
static/coimbra/accessibility.php
static/eerc/accessibility.php
static/exhibitions/accessibility.php
static/fairbairn/accessibility.php
static/geddes/accessibility.php
static/guardbook/accessibility.php
static/iconics/accessibility.php
static/iog/accessibility.php
static/jlss/accessibility.php
static/lhsacasenotes/accessibility.php
static/mimed/accessibility.php
static/openbooks/accessibility.php
static/physics/accessibility.php
static/piccolo/accessibility.php
static/pointsofarrival/accessibility.php
static/public-art/accessibility.php
static/rocks/accessibility.php
static/stcecilias/accessibility.php
static/towardsdolly/accessibility.php
static/umis/accessibility.php

Updates the dates for the accessibility statement in the available project files (accessibility.php)

Accessibility statements dates updated

---

theme/clds/views/index.php

Luc023 a 218

---

static/mimed/accessibility.php

Change month from May to July.

LUC023A-221 Change month to July

---

config/eerc.php
config/exampapers.ed.ac.uk.php
config/exhibitions.ed.ac.uk.php
config/fairbairn.ac.uk.php
config/geddes.php
config/lac-projects.is.ed.ac.uk.php
config/openbooks.is.ed.ac.uk.php
config/pointsofarrival.is.ed.ac.uk.php
config/scottishgovernmentyearbooks.ed.ac.uk.php
config/sjac-collection.is.ed.ac.uk.php
config/sopacollection.ph.ed.ac.uk.php

This branch contains updated GA4 tags for services belonging to collections.ed.ac.uk

A new GA4 Tags added

---

theme-local/openbooks/css/viewerStyle.css
theme-local/openbooks/js/pdf-viewer.js
theme/openbooks/views/header.php
theme/openbooks/views/record.php

LUC023A-228 Fixed the pdf loading error by giving the pdf viewer the full link, added code to make sure the canvas with the pdf page does not overflow over the background of the viewer and added a loading graphic so that the user knows that the viewer is working and not stuck.

LUC023A-228 - Fixed the pdf loading error and added a few QOL things

---

static/openbooks/accessibility.php

Updated the accessibility page to include a statement about the PDF reader.

LUC023A-228 Updated the accessibility page.

---

theme/art/views/header.php
theme/openbooks/views/header.php
theme/stcecilia/views/header.php
theme/stcecilia/views/index.php

Replaced the fontawesome kit number in the art header and removed it where it has been unnecessarily added in openbooks.

LUC023A-229 Replaced the fontawesome kit number.

---

theme/stcecilia/views/header.php
theme/stcecilia/views/index.php

Updated all the links that point to the test website to point to the live st cecilias website

LUC023A-231 Updated St Cecilias links

---

static/physics/accessibility.php

Updated the accessibility statement for sopacollection.phed.ac.uk and fixed the title that overlapped itself.

 LUC023A-233 Updated the accessibility statement for sopacollection.phed.ac.uk

---

static/archivemedia/accessibility.php
static/openbooks/accessibility.php
static/physics/accessibility.php

Updated the accessibility page for archives media and updated the reviewed date of openbooks accessibility page.

LUC023A-233 Archives Media and openbooks accessibility updates.

---

static/art/focus.php

Added a new section on the focus page of the art collections site. (SOUTH ASIAN ARTWORKS IN THE COLLECTIONS)

LUC023A-234 Added a new section on the focus page of the art collections site.

---

theme/guardbook/views/record.php

Added theme to guardbook for PDFs.

LUC023A-228 Guardbook fix

---

theme-local/clds/css/style.css
theme/clds/views/header.php
theme/clds/views/index.php

Added a skip to content button, improved the focus highlight and fixed the volunteering link

LUC023A-233 More accessibility fixes

---

theme/rocks/views/search_results.php

added thumbnails, changed author link from search results

LUC023A-236 search thumbnails

---

static/mimed/about.php
static/mimed/iiif.php
theme-local/coimbra-colls/css/style.css
theme-local/mimed/css/style.css
theme/coimbra-colls/views/index.php
theme/mimed/views/feedback.php
theme/mimed/views/header.php

Coimbra-Colls: Removed the sideways text on the index page and made the sections spread out over multiple rows for medium sized screens.
MIMED: broken links fixed, highlighter fixed.

LUC023A-233 Coimbra-Colls and MIMED accessibility fixes.

---

static/eerc/map.php
static/eerc/people.php
static/eerc/using-backup.php
static/eerc/using.php
static/mimed/about.php
static/mimed/iiif.php
theme-local/coimbra-colls/css/style.css
theme-local/eerc/css/style.css
theme-local/mimed/css/style.css
theme/coimbra-colls/views/index.php
theme/eerc/views/record.php
theme/mimed/views/feedback.php
theme/mimed/views/header.php

Changed the links to be a bit darker to pass contrast checks.

LUC023A-233 Mimed accessibility fixes: link colour contrast fix.

---

config/cockburn.php
theme-local/rocks/css/style.css
theme/rocks/views/header.php
theme/rocks/views/related_items.php

LUC023A-236 - changed tags in related items to display type 

---

static/art/comissioning.php
static/art/focus.php
static/art/loans.php
theme-local/art/css/style.css
theme/art/views/footer.php
theme/art/views/index.php

- All colour contrast issues have been resolved to meet WCAG 2.2 AA standards. (12/08/2024)
- [1.4.3 - Contrast (Minimum)](https://www.w3.org/TR/WCAG21/#contrast-minimum)
- Increased font size to at least 12pt (12/08/2024)
- Added a popup to notify users that a new tab is about to be opened after clicking on a link. (12/08/2024)
- [3.2.2 - On input](https://www.w3.org/TR/WCAG21/#on-input)
- Ensured that all links were underlined. (12/08/2024)
- Added a skip to main content button on each page. (12/08/2024)
- 2.[4.1 - Bypass Blocks](https://www.w3.org/TR/WCAG21/#bypass-blocks)
- The results, sort and pagination in the ‘Search’ page now warps instead of overlapping. (12/08/2024)
- [1.4.12 - Text Spacing](https://www.w3.org/TR/WCAG22/#text-spacing)
- Removed all instances of continuous …

LUC023A-233 Art Collections Website Accessibility fixes.

---

static/alumni/about.php
static/stcecilias/about.php
static/stcecilias/iiif.php
theme-local/alumni/css/style.css
theme-local/stcecilia/css/style.css
theme/alumni/views/div_main_end.php
theme/alumni/views/header.php
theme/alumni/views/index.php
theme/stcecilia/views/feedback.php
theme/stcecilia/views/footer.php
theme/stcecilia/views/header.php
theme/stcecilia/views/index.php
theme/stcecilia/views/record copy.php
theme/stcecilia/views/record.php
theme/stcecilia/views/recordfixing.php

- All colour contrast issues have been resolved to meet WCAG 2.2 AA standards. (16/08/2024)
- [1.4.3 - Contrast (Minimum)](https://www.w3.org/TR/WCAG21/#contrast-minimum)
- Increased font size to at least 12pt (16/08/2024)
- Removed all instances of continuous capitals and underlined text that were not links. (16/08/2024)
- [1.4.8 - Visual Presentation](https://www.w3.org/TR/WCAG22/#visual-presentation)
- Added a skip to main content button on each page. (16/08/2024)
- [2.4.1 Bypass Blocks](https://www.w3.org/TR/WCAG21/#bypass-blocks)
- Added a popup to notify users that a new tab is about to be opened after clicking on a link. (16/08/2024)
- [3.2.2 On input](https://www.w3.org/TR/WCAG21/#on-input)
- Implemented a consistent, high contrast focus highlighter function website wide. …

LUC023A-233 Historical Alumni website accessibility fixes.

---

static/stcecilias/about.php
static/stcecilias/iiif.php
theme-local/stcecilia/css/style.css
theme/stcecilia/views/feedback.php
theme/stcecilia/views/footer.php
theme/stcecilia/views/header.php
theme/stcecilia/views/index.php
theme/stcecilia/views/record copy.php
theme/stcecilia/views/record.php
theme/stcecilia/views/recordfixing.php

- The search bar colour contrast issues have been resolved to meet WCAG 2.2 AA standards. (16/08/2024)
- [1.4.3 - Contrast (Minimum)](https://www.w3.org/TR/WCAG21/#contrast-minimum)
- Increased font size to at least 12pt (16/08/2024)
- Changed the text alignment from justified to left aligned (16/08/2024)
- [1.4.8 - Visual Presentation](https://www.w3.org/TR/WCAG22/#visual-presentation)
- Changed text that appeared on mouse hover to also appear on keyboard focus (16/08/2024)
- [1.4.13 - Content on Hover or Focus](https://www.w3.org/TR/WCAG22/#content-on-hover-or-focus)
- Removed the transparency of the text over images. (16/08/2024)
- [1.4.5 Images of Text](https://www.w3.org/TR/WCAG22/#images-of-text)
- Added a skip to main content button on each page. (16/08/2024)
- [2.4.1 Bypass …

LUC023A-233 St Cecilias Accessibility Fixes.

---

theme/rocks/views/record.php

Fixing the manifest link which had the wrong term in the name. Not rocks, cockburn!

LUC023A-236 Fix manifest link

---

static/eerc/accessibility.php

Updated the EERC Accessibility page.

LUC023A-233 Updated the EERC Accessibility page.

---

static/eerc/accessibility.php

LUC023A-233 EERC accessibility page github merge aretefacts fixed & Link colour changed.

LUC023A-233 EERC accessibility page github merge aretefacts fixed.

---

static/eerc/accessibility.php

Removed bullet points under numbered sections where the nested bullet points used to be.

LUC023A-233 EERC Accessibility page: Bullet point fixes

---

static/alumni/accessibility.php

Accessibility statement update for alumni website.

LUC023A-233 Accessibility statement update for alumni website.

---

static/alumni/accessibility.php
static/guardbook/accessibility.php
theme-local/guardbook/css/style.css

- Changed default font sizes for Guardbook
- h1 --> 24pt
- h2 --> 20pt
- h3 --> 16pt
- p, body --> 12pt
- Updated Guardbook accessibility page
- Made sure b tag was bold for alumni accessibility page

LUC023A-233: Accessibillity page and font size updates for guardbook, accessibility page bug fix for alumni

---

static/guardbook/accessibility.php

Adding changes to the change log on guardbooks accessibilty page.

LUC023A-233 Adding changes to the change log on guardbooks accessibilty page.

---

static/cockburn/accessibility.php
theme/clds/views/header.php

Removed scaling disabling on clds. Restored bolding to the b tag on cockburn accessibility page.

LUC023A-233 removed scaling disabling on clds. Restored bolding to the b tag on cockburn accessibility page.

---

static/lhsacasenotes/accessibility.php

Accessibility statement for lhsacasenotes updated.

LUC023A-233 Accessibility statement for lhsacasenotes updated.

---

config/public-art.php

Changing ID of Public Art after accidentally loading Art images into it.

Luc023 a 242

---

static/coimbra-colls/accessibility.php

Coimbra Colls Accessibility statement update

LUC023A-233 Coimbra Colls Accessibility page update

---

static/clds/collections-as-data.php
static/clds/directory.php
theme-local/clds/css/style.css
theme/clds/views/index.php

LUC023A-233 clds new tab icon and accessibility adjustments.

LUC023A-233 clds new tab icon and accessibility adjustments.

---

theme-local/rocks/addons/mirador3/display.php
theme-local/rocks/addons/mirador3/minimalist.php

Cockburn mirador addon sanitisation.

Cockburn mirador addon sanitisation.

---

theme-local/jlss/css/style.css
theme/jlss/views/header.php

- Fix colour contrast issues
- Underline links
- Add skip to content button
- Add clear focus outline

LUC023A-233 jlss accessibility fixes

---

static/art/accessibility.php
static/iog/accessibility.php
static/stcecilias/accessibility.php

Updated WCAG links to point to WCAG22 rather than to WCAG21 and made the b tag show text in bold

Resolved accessibility statement problems

---

theme/mimed/views/record.php

LUC023A-243 Fix for non-image records
